<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>

    <RestorePackagesPath>$(MSBuildThisFileDirectory).nuget/packages</RestorePackagesPath>

    <KspDefinitionsRoot>$(MSBuildThisFileDirectory).cache/ksp/1.12.5</KspDefinitionsRoot>
    <KSPBT_GameRoot Condition="'$(KSPBT_GameRoot)' == ''">$(KspDefinitionsRoot)</KSPBT_GameRoot>
    <KSPBT_ManagedPath Condition="'$(KSPBT_ManagedPath)' == ''">$(KspDefinitionsRoot)/KSP_Data/Managed</KSPBT_ManagedPath>
  </PropertyGroup>
</Project>
